routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SubscribersController;
use App\Http\Controllers\NewsletterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth:web']], function () {
    Route::get('/newsletters-all', [NewsletterController::class, 'index'])->name('newsletters.all');
    Route::post('/newsletters-add', [NewsletterController::class, 'create'])->name('newsletters.add');

    Route::get('/subscribers-all', [SubscribersController::class, 'index'])->name('subscribers.all');
    Route::post('/subscribers-add', [SubscribersController::class, 'create'])->name('subscribers.add');

});


Auth::routes();
Route::get('/', function () {
    return redirect('login');
});

Route::get('/register', function () {
    return false;
});

app/Http/Controllers/SubscribersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Email;
use App\Models\EmailsList;
use App\Services\Filters;
use Illuminate\Http\Request;

class SubscribersController extends Controller
{
    const HTTP_200 = 200;
    const HTTP_500 = 500;

    public $per_page = 50;
    public $title;
    public $filter;
    public $file;

    public function index()
    {
        $lists = EmailsList::withCount('emails')->latest()->paginate($this->per_page);

        return view('subscribers.all', [
            'lists' => $lists
        ]);
    }

    /**
     * @param $emails
     * @param $id
     */
    public function saveEmails($emails, $id)
    {
        $data = [];
        foreach ($emails as $key => $email) {
            $data[$key]['email'] = $email;
            $data[$key]['list_id'] = $id;
            $data[$key]['created_at'] = now();
        }

        foreach (array_chunk($data, 1000) as $chunk)
            Email::insert($chunk);
    }

    public function createEmailsList($title)
    {
        return EmailsList::create(['title' => $title]);
    }

    public function create(Request $request)
    {
        $userFile = $request->file('file')->store('files');

        // New instance of Filters class
        $this->filter = new Filters($userFile);

        // Generate title when it's not present
        $title = $request->get('title') ?: uniqid();
        $validate = !$request->has('validate') ? false : true;

        if ($validate)
            $emails = $this->filter->getTrustedEmails();
        else
            $emails = $this->filter->getUniqueEmailsList();

        $this->saveEmails($emails, $this->createEmailsList($title)->id);

        return response([], self::HTTP_200);
    }
}

resources/views/subscribers/all.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInUp">

                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Списоки адресов</h5>
                        <div class="ibox-tools">
                            <a href="" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#add-subscribers">Добавить новый список</a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row m-b-sm m-t-sm">
                            <div class="col-md-12">
                                <div class="input-group">
                                    <input type="text" placeholder="Поиск" class="input-sm form-control">
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary"> Искать!</button>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="project-list">

                            <table class="table table-hover">
                                <tbody>
                                @foreach($lists as $list)
                                    <tr>
                                        <td class="project-status" width="15%">
                                            <span class="label label-primary">
                                                Адресов: {{ $list->emails_count }}
                                            </span>
                                        </td>
                                        <td class="project-title">
                                            <a href="#">{{ $list->title }}</a>
                                            <br>
                                            <small>Дата создания {{ $list->created_at->format('d.m.Y') }}</small>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@include('subscribers.modals.add')
@endsection
@section('js')
    <script>
        $(document).ready(function () {

            $('#create-subscribers-form').on('submit', function (e) {
                let form = $(this);
                let body = $('body');
                body.addClass('body-progress');
                toastr.info('Загружаем и парсим файл, нужно подождать. Ты увидишь уведомление когда я все закончу.', 'Работаем...');
                e.preventDefault();
                $.ajax({
                    method: 'POST',
                    url: '{{ route('subscribers.add') }}',
                    data: new FormData(this),
                    processData: false,
                    contentType: false,
                    success: function () {
                        toastr.success('Файлик загружен, дай мне еще 2 секундочки...', 'Наработались...');
                        setTimeout(location.reload(), 1200);
                    },
                    error: function () {
                        toastr.error('Что-то сломалось, возможно проблемный файлик?', 'Ууупс...');
                    }
                });
            });

        });
    </script>
@endsection