routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SubscribersController;
use App\Http\Controllers\NewsletterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth:web']], function () {
    Route::get('/newsletters-all', [NewsletterController::class, 'index'])->name('newsletters.all');
    Route::post('/newsletters-add', [NewsletterController::class, 'create'])->name('newsletters.add');

    Route::get('/subscribers-all', [SubscribersController::class, 'index'])->name('subscribers.all');
    Route::post('/subscribers-add', [SubscribersController::class, 'create'])->name('subscribers.add');

});


Auth::routes();
Route::get('/', function () {
    return redirect('login');
});

Route::get('/register', function () {
    return false;
});

app/Models/Newsletter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Newsletter extends Model
{
    use HasFactory;

    protected $table = 'newsletters';
    protected $fillable = [
        'title'
    ];

    public function getNewsletters()
    {
        return $this->addCounts()->latest()->get();
    }

    public function scopeAddCounts($query)
    {
        $query->withCount('messages');
        $query->withCount('deliveredMessages');
        $query->withCount('openedMessages');
        $query->withCount('clickedMessages');
        $query->withCount('complaintMessages');
        $query->withCount('permanentlyFailedMessages');
        $query->withCount('temporaryFailedMessages');

        return $query;
    }

    public function messages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id');
    }

    public function deliveredMessages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id')->where('delivered', true);
    }

    public function openedMessages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id')->where('opened', true);
    }

    public function clickedMessages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id')->where('clicked', true);
    }

    public function complaintMessages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id')->where('spam', true);
    }

    public function permanentlyFailedMessages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id')->where('permanent_fail', true);
    }

    public function temporaryFailedMessages(): HasMany
    {
        return $this->hasMany(Message::class, 'newsletter_id', 'id')->where('temporary_fail', true);
    }

}

app/Http/Controllers/NewsletterController.php
<?php

namespace App\Http\Controllers;

use App\Models\Email;
use App\Models\EmailsList;
use App\Models\Message;
use App\Models\Newsletter;
use Illuminate\Http\Request;
use Mailgun\Mailgun;

class NewsletterController extends Controller
{
    public function index(Newsletter $newsletter, EmailsList $emailsList)
    {
        $data = [
            'newsletters' => $newsletter->getNewsletters(),
            'lists' => EmailsList::withCount('emails')->latest()->get()
        ];

        return view('newsletters.all', $data);
    }

    /**
     * Send emails
     *
     * @param $emails
     * @param $json
     * @param $view
     */
    public function mailgunInstance($emails, $json, $view)
    {
        $mailgun = Mailgun::create(env('MAILGUN_SECRET'), env('MAILGUN_ENDPOINT'));
        $mailgun->messages()->send(env('MAILGUN_DOMAIN'), [
            'from' => env('MAIL_FROM'),
            'to' => $emails,
            'subject' => 'Sincere Systems Group',
            'html' => $view,
            'recipient-variables' => $json,
            'o:tracking-opens' => 'yes',
            'o:tracking-clicks' => 'yes',
            'v:message_id' => '%recipient.message_id%',
        ]);
    }

    public function buildMessages($newsletter_id, $emails)
    {
        $result = [];
        foreach ($emails as $key => $email) {
            $result[$key]['email_id'] = $email->id;
            $result[$key]['newsletter_id'] = $newsletter_id;
            $result[$key]['list_id'] = $email->list_id;
            $result[$key]['created_at'] = now();
        }

        return $result;
    }

    public function addMessages($data)
    {
        foreach (array_chunk($data, 1000) as $chunk)
            Message::insert($chunk);
    }

    public function create(Request $request, Email $emails, Newsletter $newsletter)
    {
        $view = view('mail.html')->render();
        $list = $emails->doesntHave('blockedEmail')->where('list_id', $request->id)->get();
        $newsletter_id = $newsletter->create($request->all())->id;

        $messages = $this->buildMessages($newsletter_id, $list);
        $this->addMessages($messages);

        Message::with('email')
            ->where('newsletter_id', $newsletter_id)
            ->chunkById(1000, function ($messages) use ($view) {
                $emails = [];
                $json = [];
                foreach ($messages as $key => $messsage) {
                    $json[$messsage->email->email] = ['message_id' => $messsage->id];
                    $emails[] = $messsage->email->email;
                }
                $json = json_encode($json);

                $this->mailgunInstance($emails, $json, $view);
            });
    }
}

resources/views/newsletters/all.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInUp">

                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Рассылки</h5>
                        <div class="ibox-tools">
                            <a href="" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#add-newsletter">Создать рассылку</a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="project-list">

                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Messages</th>
                                        <th>Delivered</th>
                                        <th>Bounce</th>
                                        <th>Opened</th>
                                        <th>Clicked</th>
                                        <th>Complained</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($newsletters as $list)
                                    <tr>
                                        <td class="project-title">
                                            <a href="#">{{ $list->title }}</a>
                                            <br>
                                            <small>Дата создания {{ $list->created_at->format('d.m.Y h:i') }}</small>
                                        </td>
                                        <td>
                                            <b>{{ $list->messages_count }}</b>
                                        </td>
                                        <td>
                                            {{ $list->delivered_messages_count }}
                                        </td>
                                        <td>
                                            <b>{{ $list->permanently_failed_messages_count }}</b>
                                        </td>
                                        <td>
                                            {{ $list->opened_messages_count }}
                                        </td>
                                        <td>
                                            {{ $list->clicked_messages_count }}
                                        </td>
                                        <td>
                                            {{ $list->complaint_messages_count }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@include('newsletters.modals.add', ['lists' => $lists])
@endsection
@section('js')
    <script>
        $(document).ready(function () {

            $('#create-newsletter-form').on('submit', function (e) {
                let form = $(this);
                let body = $('body');
                body.addClass('body-progress');
                toastr.info('Загружаем и парсим файл, нужно подождать. Ты увидишь уведомление когда я все закончу.', 'Работаем...');
                e.preventDefault();
                $.ajax({
                    method: 'POST',
                    url: '{{ route('newsletters.add') }}',
                    data: new FormData(this),
                    processData: false,
                    contentType: false,
                    success: function () {
                        toastr.success('Письма отправлены, дай мне еще 2 секундочки...', 'Наработались...');
                        setTimeout(location.reload(), 1200);
                    },
                    error: function () {
                        toastr.error('Что-то сломалось, попробуй перегазгрузить страничку!', 'Ууупс...');
                    }
                });
            });

        });
    </script>
@endsection